### ISSUE TITLE
Mezzio skeleton does not work with `mezzio/mezzio-tooling` v2+

### ISSUE THREAD

**Issue by devbeta** [mezzio/mezzio-skeleton#58] opened 2021-11-09 13:36 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.10.0

#### Summary

Versions of mezzio/mezzio-tooling prior to v2.0 exposed a `vendor/bin/mezzio` binary, but now this package exposes commands for laminas-cli, and may be invoked via `vendor/bin/laminas`.

#### Current behavior

The command `composer mezzio` is broken now.

#### How to reproduce

```
> composer mezzio
```

#### Expected behavior

Need to replace `"mezzio": "mezzio --ansi"` with `"mezzio": "laminas --ansi"` in the "scripts" section of the composer.json file.

**Comment by boesing** [comment] 2021-11-10 14:51
I've updated this issue as this actually is not a bug - its just not (yet) supported.

**Comment by lukaslangen** [comment] 2021-12-23 10:51
Can be closed as #60 fixed this.

**Comment by Ocramius** [comment] 2021-12-23 10:53
Awesome, thanks @lukaslangen!

**Closed as completed by Ocramius** 2021-12-23 10:53 UTC
Labels: Feature Request
